"""expand simulation model

Revision ID: 0bbe6d7cfa56
Revises: d4b7a9e2c631
Create Date: 2026-08-24 15:07:33.361642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbe6d7cfa56'
down_revision: Union[str, Sequence[str], None] = 'd4b7a9e2c631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('dataset_id', sa.UUID(), nullable=False))
    op.add_column('simulations', sa.Column('intervention_type', sa.String(length=50), nullable=False))
    op.add_column('simulations', sa.Column('target_segment', sa.String(length=50), nullable=False))
    op.add_column('simulations', sa.Column('intensity_percentage', sa.Integer(), nullable=False))
    op.add_column('simulations', sa.Column('targeted_customers', sa.Integer(), nullable=False))
    op.add_column('simulations', sa.Column('estimated_customers_retained', sa.Integer(), nullable=False))
    op.add_column('simulations', sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('simulations', sa.Column('roi', sa.Numeric(precision=10, scale=4), nullable=False))
    op.alter_column('simulations', 'predicted_churn_reduction',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    op.alter_column('simulations', 'estimated_revenue_saved',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.create_index(op.f('ix_simulations_dataset_id'), 'simulations', ['dataset_id'], unique=False)
    op.create_foreign_key(None, 'simulations', 'datasets', ['dataset_id'], ['id'])
    op.drop_column('simulations', 'discount_percentage')
    op.drop_column('simulations', 'strategy_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('strategy_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('simulations', sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'simulations', type_='foreignkey')
    op.drop_index(op.f('ix_simulations_dataset_id'), table_name='simulations')
    op.alter_column('simulations', 'estimated_revenue_saved',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('simulations', 'predicted_churn_reduction',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    op.drop_column('simulations', 'roi')
    op.drop_column('simulations', 'estimated_cost')
    op.drop_column('simulations', 'estimated_customers_retained')
    op.drop_column('simulations', 'targeted_customers')
    op.drop_column('simulations', 'intensity_percentage')
    op.drop_column('simulations', 'target_segment')
    op.drop_column('simulations', 'intervention_type')
    op.drop_column('simulations', 'dataset_id')
    # ### end Alembic commands ###
